### ISSUE TITLE
[BUG] Error on first dev run

### ISSUE THREAD

**Issue by themes-disco** [blanklob/adastra#12]
┏━━ Error ━━━━━━━━━━━━━━━━━━
┃ The option --overwrite-json is not supported.
┗━━━━━━━━━━━━━━━━━━━━━━━

![image](https://user-images.githubusercontent.com/110619737/218815725-4667a52a-502f-46bb-9a53-0ad205aded77.png)

My config:
node --version
v16.14.0

yarn --version
1.22.19

shopify version
3.43.0

**Comment by blanklob** [comment]
Hey thank for reporting this I will look into it

**Comment by blanklob** [comment]
Issue has been fixed make sure you use the latest Shopify CLI 3 thanks again

**Comment by themes-disco** [comment]
@blanklob I got the same error and I have the last version of shopify CLI (3.43.0)
